<!DOCTYPE html>
<html>
<head>
	<title>HTML & CSS cource</title>
	<style type="text/css" media="screen">
		body{
			font-family:arial,sans-sarif;
			background:gray;
		}
		header{
			background:black;
			color:yellow;
			width:80%;
			margin-right:auto;
			margin-left:auto;
			text-align:center;
		}
		footer{
			background: black;
			color:yellow;
			width:80%;
			margin-left:auto;
			margin-right: auto;
			text-align: center;
		}
		section{
			background:white;
			width:80%;
			margin-left: auto;
			margin-right: auto;
		}

	</style>
</head>
<body>
	<header>
		<hgroup>
		<h1>HTML & CSS Cource</h1>
		<h2>WebDegine Cource in telugu</h2>
		</hgroup>
	</header>

	<section>
		<article>
		<h1>My First Article</h1>
			<p>While working with technologies the programmer has to dvelop both common logic and specific logics of application.</p>
<p>While working with frameworks the programmer has to develop only application specific logics because the common logics will be generated by the framework dynamically.</p>
<p>Every framework uses technology internally but it never make program to know about it. This is nothing but providing abstraction layer (hiding implementations/internals)
</p>
			
			
		</article>
	</section>

	<footer>
	
www.harishworld.com© 
	</footer>
</body>

</html>